### ISSUE TITLE
With requirejs, when running 2 series of tests;  the second fails 

### ISSUE THREAD

**Issue by superseby** [flightjs/mocha-flight#15]
Hello, 
I am using mocha-flight via require.js. 
This is how tests are running : 
```
require([
    'chai',
    'chai-jquery',
    'mocha-flight'
], function(chai, chaiJquery ) {
     chai.use(chaiJquery);
     mocha.setup('mocha-flight');
     expect = chai.expect;

     require([
          'spec/join2.spec.js',
          'spec/join.spec.js'
     ], function() {
          mocha.run();
     });
});
```

join2 and join are tests to the same component; When run separately everything is fine. When trying to run one after another, I ve got this exception

```
"before each" hook ‣
TypeError: object is not a function
    at suite.on.context.setupComponent (http://localhost:8000/app/static/js/bower_components/mocha-flight/lib/mocha-flight.js?bust=1426351700984:259:26)
```
Something I am doing wrong or is this a bug ?

Thanx for your time !

Sebastien

**Comment by razmig** [comment]
Having the same issue, @superseby have you come with a solution?

**Comment by schmilblick** [comment]
+1 ping @necolas

**Comment by jared-stilwell** [comment]
@superseby / @razmig, trying to put together a reduced test case for this; do you mind giving me a sample from your spec files?

**Comment by razmig** [comment]
What i am guessing the issue is that the second test suite context is getting polluted by the first suite after.
The mocha-flight tear dawn the component but pollutes the context for the second suite
The error i get is when we do new crx.Component() and the error is 'Object is not function' and when i debug i get suite.ctx is an object with the following attrs {$node:null, component:null, Component:null}
I use grunt-mocha-test as grunt package and i use requirejs to load the flight libs and my flight components

Sent from Outlook




On Tue, May 19, 2015 at 2:47 PM -0700, "Jared Stilwell" <notifications@github.com> wrote:












@superseby / @razmig, trying to put together a reduced test case for this; do you mind giving me a sample from your spec files?

**Comment by razmig** [comment]
The js error i get in this (new crx.Component()) happens only for the second suite. The first suite passes 

Sent from Outlook




On Tue, May 19, 2015 at 2:47 PM -0700, "Jared Stilwell" <notifications@github.com> wrote:












@superseby / @razmig, trying to put together a reduced test case for this; do you mind giving me a sample from your spec files?

**Comment by necolas** [comment]
Hi, I don't maintain this repo. Hopefully @jared-stilwell will be able to help.

**Comment by jared-stilwell** [comment]
@razmig Full marks. I'm able to reproduce this by placing multiple describeComponent() calls in the describe_component.spec.js test.

**Comment by jared-stilwell** [comment]
Just issued PR #17 which should address this

**Comment by razmig** [comment]
Great work @jared-stilwell I can confirm the issue has been fixed

**Comment by kieran-bamforth** [comment]
Thank you for the update Jared, I have spent all day trying to figure this out and have only just come across your solution. 

Please could we get this tagged and pushed to bower? Bower is giving out an old tag (0.4) that does not contain this fix. It would have saved me a lot of stress!
